title: NeuroMesh Whitepaper
description: NeuroMesh Whitepaper
baseurl: ""
url: ""
markdown: kramdown
kramdown:
  toc_levels: 1..3
  math_engine: mathjax
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
